### ISSUE TITLE
Add customizable "extra actions" for tests and sessions

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#290]
Should be something like:

```
extra_session_actions:
    - title: Do Something
      url: ...
      method: post/get
      icon_url: ...
```
